# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-22 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(default='')),
                ('idHotel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('url', models.URLField()),
                ('direccion', models.TextField(max_length=200)),
                ('descripcion', models.TextField(default='')),
                ('estrellas', models.CharField(max_length=32)),
                ('tipo', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_I', models.URLField(default='')),
                ('idHotel', models.IntegerField(default=0)),
                ('img', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Hoteles.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('titulo_pagina', models.CharField(max_length=32)),
                ('hoteles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoteles.Hotel')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoteles.Hotel'),
        ),
    ]
