# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160517050722 on 2016-05-17 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('estrellas', models.IntegerField()),
                ('url', models.URLField()),
                ('direccion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StyleCSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(blank=True)),
                ('banner', models.TextField(blank=True)),
                ('login', models.TextField(blank=True)),
                ('menu', models.TextField(blank=True)),
                ('pie', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('titulo_pagina', models.CharField(max_length=32)),
                ('hoteles', models.ManyToManyField(to='Hoteles.Hotel')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='hotel',
            field=models.ManyToManyField(to='Hoteles.Hotel'),
        ),
    ]
