# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 11:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(default='')),
                ('idHotel', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('url', models.URLField()),
                ('direccion', models.TextField(max_length=200)),
                ('descripcion', models.TextField(default='')),
                ('estrellas', models.CharField(max_length=32)),
                ('tipo', models.CharField(default='', max_length=32)),
                ('urlimagen', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHotel', models.IntegerField(default='')),
                ('usuario', models.CharField(max_length=32)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_I', models.URLField(default='')),
                ('idHotel', models.IntegerField(default=0)),
                ('img', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Hoteles.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='StyleCSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='', max_length=300)),
                ('size', models.CharField(default='', max_length=200)),
                ('titulo_pagina', models.CharField(default='', max_length=32)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoteles.Hotel'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
