# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagen',
            new_name='Image',
        ),
    ]
