# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0002_hotelselect_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='usuario',
            new_name='nombre',
        ),
    ]
