# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-22 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0002_stylecss'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='urlimagen',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
