# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-22 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0003_hotel_urlimagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Imagen',
        ),
    ]
