# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0003_auto_20160626_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='nombre',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='hotelselect',
            name='hotel',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, to='Hoteles.Hotel'),
        ),
    ]
