# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-22 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0004_auto_20160522_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylecss',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='stylecss',
            name='login',
        ),
        migrations.RemoveField(
            model_name='stylecss',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='stylecss',
            name='pie',
        ),
        migrations.AddField(
            model_name='stylecss',
            name='color',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='stylecss',
            name='size',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stylecss',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoteles.Usuarios'),
        ),
    ]
