# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0005_auto_20160522_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='hoteles',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='hoteles',
            field=models.ManyToManyField(to='Hoteles.Hotel'),
        ),
    ]
