# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-22 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0006_auto_20160621_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='titulo_pagina',
        ),
        migrations.AddField(
            model_name='stylecss',
            name='titulo_pagina',
            field=models.CharField(default='', max_length=32),
        ),
    ]
