# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0007_auto_20160622_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHotel', models.IntegerField(default='')),
                ('usuario', models.CharField(max_length=32)),
                ('fecha', models.DateField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='hoteles',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='idHotel',
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='stylecss',
            name='usuario',
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
