# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0007_auto_20160622_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
