# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0008_auto_20160623_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hotelselect',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
