# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0008_usuarios_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
