# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0009_auto_20160623_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='hotelselect',
            name='fecha',
        ),
    ]
