# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0009_auto_20160624_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(default='')),
                ('idHotel', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoteles.Hotel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoteles.Usuarios')),
            ],
        ),
    ]
