# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hoteles', '0010_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoteleSeleccionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seleccion', models.DateField(blank=True, null=True)),
                ('idHotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoteles.Hotel')),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='hoteles',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stylecss',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
