# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0011_auto_20160625_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylecss',
            old_name='titulo_pagina',
            new_name='titulo',
        ),
    ]
