# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0012_auto_20160625_0951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StyleCSS',
            new_name='CSS',
        ),
    ]
