# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0013_auto_20160625_0952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HoteleSeleccionado',
            new_name='SelectedHotel',
        ),
    ]
